version: '3.7'

services:
  database:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgres_pass_1234@!@#
      - POSTGRES_DB=postgresdb
    volumes:
    - database-data:/var/lib/postgresql/data/
    expose:
    - 5432
    networks:
      - db-network

  scraper:
    build:
      context: scraper
      dockerfile: Dockerfile
    command: python3 dispatcher.py
    ports: # use expose instead sinc internal service
      - 40:3204
    environment:
      - PORT=3204
    networks:
      - rpc-network

  main-service:
    build:
      context: typegraph-server
      dockerfile: Dockerfile
    command: npm run start
    ports: 
      - 80:4000
    environment:
      - PORT=4000
    depends_on:
      - database
      - scraper
    networks:
      - db-network
      - rpc-network
    
networks:
  db-network:
  rpc-network:

volumes: 
  database-data: